### ISSUE TITLE
Does this work on MacOS?

### ISSUE THREAD

**Issue by richcorbs** [ColasNahaboo/cgibashopts#10]
Hey, this project looks interesting but I'm not having success on Mac where I'm developing.

My upload file is written to the tmp directory with 0 bytes.

The command I'm using to upload is `curl -F file=@index.html.tgz https://localhost/upload`. The output seems to show the right number of bytes.

When I run the test suite on Mac I get:

`find: illegal option -- t`

and

`grep: invalid option -- P`

Any advice on these errors?

Thanks!

**Comment by ColasNahaboo** [comment]
Sorry, It requires the GNU version of the unix utilities, not the crippled ones shipped by Apple.

Installing the the GNU versions of bash, coreutils, grep, sed  should do the trick.

I don't use MacOS (an historical open source foe) but I read there are solutions, such as the ones listed in https://apple.stackexchange.com/questions/69223/how-to-replace-mac-os-x-utilities-with-gnu-core-utilities

**Comment by richcorbs** [comment]
Thanks. Installing the GNU versions of the utilities worked perfectly!

**Comment by ColasNahaboo** [comment]
Thanks for your feedback!
I update the doc to mention this.
