### ISSUE TITLE
File is truncated to nothing

### ISSUE THREAD

**Issue by ghost** [ColasNahaboo/cgibashopts#6]
Hi, need to run server to make my canon lbp-810 become wifi-printer, using busybox httpd, for cgi i use bash. found this lib, but when i upload pdf file, everything it have is:
```pdf
%PDF-1.3
```
when i upload a txt, it is full (tho it is one line, will try something larger...). when i upload a jpeg, it is printing the blank page, will try to analyze the jpeg is it even have something.
so, why does it truncate the pdf to just header?
thanks

**Comment by ColasNahaboo** [comment]
Interesting, I did not try cgibashopts with busybox.

Do you use only httpd from busybox, or all the busybox commands (grep, sed, ...)?

And more importantly, do you use bash, or busybox shell, ash?

Could you try to run the cgibashopts test suite in your environment? Run `tests/tewiba -v`
The test suite simulate 5 files uploads, text and binary, in various browsers (linux, firefox, windows, ...)
The "file4" is the binary file used in the tests to simulate a browser upload. 

Could you send me a file reproducing the problem when uploaded on your setup?

**Comment by ghost** [comment]
> Do you use only httpd from busybox, or all the busybox commands (grep, sed, ...)?

It is alpine linux, all commands are busybox

> And more importantly, do you use bash, or busybox shell, ash?

Bash

> Could you try to run the cgibashopts test suite in your environment?

Will try this

> Could you send me a file reproducing the problem when uploaded on your setup?

This one: http://www.africau.edu/images/default/sample.pdf

**Comment by ghost** [comment]
Tbh i found other solution for this, https://codereview.stackexchange.com/a/79626

**Comment by ColasNahaboo** [comment]
OK, I suspect this is due to some difference of alpine linux with the debian/ubuntu systems I use.

Did you install other packages than bash on your alpine linux?

I may try to install an alpine linux somewhere and test your setup.

**Comment by ghost** [comment]
> Did you install other packages than bash on your alpine linux?

```sh
[pi] www> apk info | wc -l
197
```

**Comment by ghost** [comment]
Oh yes, it is Raspberry Pi 3B, arm64

**Comment by ghost** [comment]
> Could you try to run the cgibashopts test suite in your environment?

[test.log](https://github.com/ColasNahaboo/cgibashopts/files/7799370/test.log)

**Comment by ColasNahaboo** [comment]
Ah the test log seems to indicate that busybox grep is not powerful enough. You may want to try to install the grep package.

**Comment by ghost** [comment]
> Ah the test log seems to indicate that busybox grep is not powerful enough. You may want to try to install the grep package.

okay i will try. but that solution that i found is working. but i ll anyway install grep and tun tests again

**Comment by ColasNahaboo** [comment]
Thanks anyways for your report!
I have added a warning for the busybox case in the README.

**Comment by ghost** [comment]
Okay, i installed GNU grep, sed, coreutils, now everything is working. Could you add a note that to make it work you need to have GNU versions instead of BB?

**Comment by ColasNahaboo** [comment]
Yes, of course, thanks a lot!

**Comment by ghost** [comment]
Thanks! I ll close this as it is solved
