### ISSUE TITLE
Error at multipart/form-data on CentOS Stream release 8

### ISSUE THREAD

**Issue by florin-ctu** [ColasNahaboo/cgibashopts#9]
[version 4.1.1]

`# ./tests/tewiba -v`
`== Sourcing __INIT__`
`All tests OK ==`
`# ./tests/RUN-ALL-TESTS`
produce no output

-------------------------
POST http://e.com/cgi-bin/TEST HTTP/1.1
Host: e.com
Connection: Keep-Alive
Content-Type: multipart/form-data, boundary=ahp1bnc4hlafmnvyuay783qlh9k1uv76
Content-Length: 2334
Connection: close

--ahp1bnc4hlafmnvyuay783qlh9k1uv76
Content-Disposition: form-data; name="url"

https://some.url
--ahp1bnc4hlafmnvyuay783qlh9k1uv76
Content-Disposition: form-data; name="auth"

a0b50b5db9d
--ahp1bnc4hlafmnvyuay783qlh9k1uv76
Content-Disposition: form-data; name="method"

POST
--ahp1bnc4hlafmnvyuay783qlh9k1uv76
Content-Disposition: form-data; name="send_content_type"

application/xml
--ahp1bnc4hlafmnvyuay783qlh9k1uv76
Content-Disposition: form-data; name="receive_content_type"

application/xml
--ahp1bnc4hlafmnvyuay783qlh9k1uv76
Content-Disposition: form-data; name="json2xml"

Y
--ahp1bnc4hlafmnvyuay783qlh9k1uv76
Content-Disposition: form-data; name="data"; filename="file.xml"
Content-Type: application/xml

`<?xml version="1.0" encoding="UTF-8"?><e...e>`
--ahp1bnc4hlafmnvyuay783qlh9k1uv76--

-------------------------
`source ./cgibashopts`
`echo "$FORMS"`

will output
`ahp1bnc4hlafmnvyuay783qlh9k1uv76ContentDispositionformdataname name name name name name name filename`

**Comment by florin-ctu** [comment]
the issue was at line 86 of cgibashopts
`    if [[ ${CONTENT_TYPE:-} =~ ^multipart/form-data\;[[:space:]]*boundary=([^\;]+) ]]; then`
I change to
`   if [[ ${CONTENT_TYPE:-} =~ ^multipart\/form-data[\;\,][[:space:]]*boundary=([^\;]+) ]]; then`

as in this case
`CONTENT_TYPE='multipart/form-data, boundary=ahp1bnc4hlafmnvyuay783qlh9k1uv76'

**Comment by ColasNahaboo** [comment]
Thanks for the report.
Fixed at v4.1.2
